Update build-test-release.yml

diff --git a/.github/workflows/build-test-release.yml b/.github/workflows/build-test-release.yml
--- a/.github/workflows/build-test-release.yml
+++ b/.github/workflows/build-test-release.yml
@@ -143,12 +143,19 @@ jobs:
       #     sed -i 's/172.16.0.18/kubernetes:8443/g' $KUBECONFIG
       #     sudo ssh -4 -fN -F /home/runner/.ssh/config -L0.0.0.0:8443:172.16.0.18:443 nexus
 
-      - name : Print JIRA ID from Title of PR
+      - name : Get JIRA ID from Title of PR
         if: ${{ github.event_name }} == 'pull_request'
         run: |
-            echo The Title of your PR is ${{ github.event.pull_request.title }}
+            echo Extracting Jira Id from PR Title: ${{ github.event.pull_request.title }}
+            echo PR titile should have Jira Id enclosed in a pair of square brackers like [AR-419]
             echo ${{ github.event.pull_request.title }} | sed -n 's/.*\[\(.*\)\].*/\1/p'
-            echo "::set-output name=jira_id::$(echo ${{ github.event.pull_request.title }} | sed -n 's/.*\[\(.*\)\].*/\1/p')"
+            if [[ $? == 0 ]] 
+            then
+              echo "::set-output name=jira_id::$(echo ${{ github.event.pull_request.title }} | sed -n 's/.*\[\(.*\)\].*/\1/p')"
+            else
+              echo "Jira Id not found in PR Title"
+              echo "Jira Id should be included in PR Title enclosed in a pair of square brackers like [AR-419]" 
+            fi  
         id: extract_jira_id 
       
       - name : Validate Jira ID
